---
title: "Detection of Pneumonia from Chest X-Ray Images"
author: "Antonio Esteves"
output:
  html_document:
    theme: readable
    df_print: paged
    toc: yes
  html_notebook:
    fig_width: 7
    theme: readable
    toc: yes
    toc_float: yes
---

```{r echo=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
theme_set(theme_bw())

library(broom)
library(pROC)
library(fbroc)
knitr::opts_chunk$set(tidy = FALSE,
                      fig.width = 6,
                      fig.height = 5)

```

## Leitura dos Dados

```{r read}
dados = read_csv("../data/rocObj.csv")
glimpse(dados)
```

## Curva ROC e AUC

```{r}
par(pty = "s")
rocObj = dados %>% 
  roc(y_true,y_pred, plot=TRUE, legacy.axes=TRUE, percent = TRUE, xlab = "False Positive Percentage", ylab= "True Positive Percentage", col="#377eb8", lwd=4, partial.auc=c(100,82), auc.polygon=TRUE, auc.polygon.col="#377eb822")
ggsave("ROC_curve_partial.pdf", width = 6, height = 4)

par(pty = "s")
rocObj = dados %>% 
  roc(y_true,y_pred, plot=TRUE, legacy.axes=TRUE, percent = TRUE, xlab = "False Positive Percentage", ylab= "True Positive Percentage", col="#377eb8", lwd=4)
ggsave("ROC_curve.pdf", width = 6, height = 4)
```

```{r}
obj = dados %>% 
  roc(y_true, y_pred, ci=TRUE, plot=FALSE)
# obj["ci"]

ciobj = ci.se(obj, specificities=seq(0, 1, l=25), boot.n=10000)
dat.ci <- data.frame(x = as.numeric(rownames(ciobj)),
                     lower = ciobj[, 1],
                     upper = ciobj[, 3])

ggroc(obj) + 
  theme_minimal() + 
  geom_abline(slope=1, intercept = 1, linetype = "dashed", alpha=0.7, color = "grey") + 
  coord_equal() + 
  geom_ribbon(data = dat.ci, aes(x = x, ymin = lower, ymax = upper), fill = "steelblue", alpha= 0.2) + 
  ggtitle(capture.output(obj$ci))
  ggsave("ICS_ROC_curve.pdf", width = 6, height = 4)
```

## Intervalos de Confiança

```{r}
ci.auc(rocObj, conf.level=0.95, method="bootstrap", boot.n = 10000, boot.stratified = TRUE, reuse.auc=TRUE,
progress = getOption("pROCProgress")$name, parallel=FALSE)
```

```{r}
# Utilizando a biblioteca fbroc

new_data = dados %>% 
  mutate(true_class = as.logical(y_true))

result.boot = boot.roc(new_data$y_pred, new_data$true_class, n.boot = 10000)
perf(result.boot, "auc", conf.level = 0.95)
conf(result.boot, steps = 10000)
# plot(result.boot)
```

## Com teste de hipótese

```{r}
# https://stats.stackexchange.com/questions/75050/in-r-how-to-compute-the-p-value-for-area-under-roc


```


```{r}
# https://cran.r-project.org/web/packages/scifigure/vignettes/Visualizing_Scientific_Replication.html

library(scifigure)
exps = init_experiments(2, c("Kermany et al. 2018", "Reprodução"))
exps["analysis_plan", 2] = "unobserved"
exps["analysis_plan", 2] = "unobserved"
exps[c("experimenter", "analyst", "estimate", "claim"), 2] = "different"
sci_figure(exps, hide_stages = c("population", "hypothesis"), diff = TRUE)
ggsave("sci_figure.pdf", width = 6, height = 4)

```

